const router = require('express').Router();
const { verifyToken, roleCheck } = require('../middleware/authMiddleware');
const c = require('../controllers/adminController');
router.use(verifyToken, roleCheck('admin'));
router.get('/dashboard', c.getDashboard);
router.get('/orders', c.getAllOrders);
router.put('/orders/:id', c.updateOrder);
router.get('/canteens', c.getAllCanteens);
router.put('/canteens/:id', c.updateCanteen);
router.get('/grievances', c.getAllGrievances);
router.put('/grievances/:id/reply', c.replyGrievance);
router.get('/refunds', c.getAllRefunds);
router.put('/refunds/:id/process', c.processRefund);
router.get('/analytics', c.getAnalytics);
module.exports = router;
