const router = require('express').Router();
const { verifyToken, roleCheck } = require('../middleware/authMiddleware');
const c = require('../controllers/grievanceController');
router.use(verifyToken);
router.post('/', roleCheck('student'), c.create);
router.get('/my', roleCheck('student'), c.getMy);
router.get('/vendor', roleCheck('vendor'), c.getVendorGrievances);
router.get('/all', roleCheck('admin'), c.getAllGrievances);
router.put('/:id/status', c.updateStatus);
router.post('/:id/ai-reply', c.aiReply);
module.exports = router;
