const router = require('express').Router();
const { verifyToken, roleCheck } = require('../middleware/authMiddleware');
const c = require('../controllers/orderController');
router.use(verifyToken);
router.post('/', roleCheck('student'), c.placeOrder);
router.get('/my', roleCheck('student'), c.getMyOrders);
router.get('/:id', c.getOrder);
router.get('/:id/track', c.trackOrder);
router.put('/:id/cancel', roleCheck('student'), c.cancelOrder);
module.exports = router;
